title: Agartha Yazılım
description: "Agartha Yazılım ve Oyun Topluluğu"
author:
  name: "Agartha"
  email: "sahanhasretankara@gmail.com"
  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Agartha"
year : "2020"
